from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class DataSource:
    key: str
    title: str
    variables: tuple[str, ...]
    temporal_resolution: str
    spatial_resolution: str
    provider: str
    method: str
    params: dict = field(default_factory=dict)
    aliases: tuple[str, ...] = field(default_factory=tuple)
    format_hints: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""
    official_url: str = ""
    access_mode: str = ""
    auth_required: bool = False
    product_notes: str = ""


DEFAULT_SOURCES: tuple[DataSource, ...] = (
    DataSource(
        key="chirps_monthly_nc",
        title="CHIRPS monthly NetCDF",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="0.05 degree",
        provider="Climate Hazards Center",
        method="http_direct",
        params={
            "base_url": "https://data.chc.ucsb.edu/products/CHIRPS/v3.0/monthly/global/netcdf/by_year/",
            "filename_pattern": "chirps-v3.0.{year}.monthly.nc",
            "time_expansion": "year",
        },
        aliases=("chirps",),
        format_hints=("NetCDF",),
        notes="CHIRPS v3 monthly global NetCDF by_year files.",
        official_url="https://data.chc.ucsb.edu/products/CHIRPS/v3.0/",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Downloader targets monthly/global/netcdf/by_year.",
    ),
    DataSource(
        key="chirps_daily_tif",
        title="CHIRPS daily GeoTIFF",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.05 degree",
        provider="Climate Hazards Center",
        method="http_direct",
        params={
            "base_url": "https://data.chc.ucsb.edu/products/CHIRPS/v3.0/daily/final/sat/",
            "filename_pattern": "chirps-v3.0.sat.{year}.{month}.{day}.tif",
            "directory_pattern": "{year}/",
            "time_expansion": "date",
        },
        format_hints=("GeoTIFF",),
        notes="CHIRPS v3 daily final satellite GeoTIFF files.",
        official_url="https://data.chc.ucsb.edu/products/CHIRPS/v3.0/",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Downloader targets daily/final/sat/YYYY/chirps-v3.0.sat.YYYY.MM.DD.tif.",
    ),
    DataSource(
        key="gpcc_full_daily_v2022_10_nc_gz",
        title="GPCC Full Data Daily Version 2022 at 1.0 degree",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="1.0 degree",
        provider="DWD GPCC",
        method="http_direct",
        params={
            "base_url": "https://opendata.dwd.de/climate_environment/GPCC/full_data_daily_v2022/",
            "filename_pattern": "full_data_daily_v2022_10_{year}.nc.gz",
            "time_expansion": "year",
        },
        aliases=("gpcc", "gpcc_daily"),
        format_hints=("NetCDF", "GZip"),
        notes="GPCC daily product exposed as annual gzipped NetCDF files.",
        official_url="https://opendata.dwd.de/climate_environment/GPCC/full_data_daily_v2022/",
        access_mode="direct_http",
        auth_required=False,
        product_notes="One annual file per year from 1982 onward.",
    ),
    DataSource(
        key="gpcc_full_monthly_v2022_025_nc_gz",
        title="GPCC Full Data Monthly Version 2022 at 0.25 degree",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="0.25 degree",
        provider="DWD GPCC",
        method="http_direct",
        params={
            "base_url": "https://opendata.dwd.de/climate_environment/GPCC/full_data_monthly_v2022/025/",
            "filename_pattern": "full_data_monthly_v2022_{start_year}_{end_year}_025.nc.gz",
            "time_expansion": "decade",
            "decade_anchor_year": 1891,
            "decade_length": 10,
        },
        aliases=("gpcc_monthly",),
        format_hints=("NetCDF", "GZip"),
        notes="GPCC monthly 0.25 degree product exposed as decadal gzipped NetCDF files.",
        official_url="https://opendata.dwd.de/climate_environment/GPCC/full_data_monthly_v2022/025/",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Downloader selects all decadal blocks overlapping the requested period.",
    ),
    DataSource(
        key="cpc_global_unified_daily_nc",
        title="CPC Global Unified Gauge-Based Daily Precipitation",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.5 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/cpc_global_precip/",
            "filename_pattern": "precip.{year}.nc",
            "time_expansion": "year",
        },
        aliases=("cpc", "cpc_global_daily"),
        format_hints=("NetCDF",),
        notes="CPC global daily precipitation annual NetCDF files.",
        official_url="https://psl.noaa.gov/data/gridded/data.cpc.globalprecip.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Annual files are distributed from the NOAA PSL THREDDS fileServer path.",
    ),
    DataSource(
        key="udel_precip_monthly_v501_nc",
        title="University of Delaware monthly land precipitation v5.01",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="0.5 degree",
        provider="NOAA PSL / University of Delaware",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/udel.airt.precip/",
            "filename_pattern": "precip.mon.total.v501.nc",
            "time_expansion": "none",
        },
        aliases=("udel", "udel_precip"),
        format_hints=("NetCDF",),
        notes="University of Delaware land-only monthly precipitation time series served from the NOAA PSL THREDDS fileServer.",
        official_url="https://psl.noaa.gov/data/gridded/data.UDel_AirT_Precip.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Current v5.01 precipitation file is distributed as a single NetCDF file.",
    ),
    DataSource(
        key="udel_air_monthly_v501_nc",
        title="University of Delaware monthly land air temperature v5.01",
        variables=("air_temperature", "temperature"),
        temporal_resolution="monthly",
        spatial_resolution="0.5 degree",
        provider="NOAA PSL / University of Delaware",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/udel.airt.precip/",
            "filename_pattern": "air.mon.mean.v501.nc",
            "time_expansion": "none",
        },
        aliases=("udel_air",),
        format_hints=("NetCDF",),
        notes="University of Delaware land-only monthly air temperature time series served from the NOAA PSL THREDDS fileServer.",
        official_url="https://psl.noaa.gov/data/gridded/data.UDel_AirT_Precip.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Current v5.01 air-temperature file is distributed as a single NetCDF file.",
    ),
    DataSource(
        key="precl_monthly_05deg_nc",
        title="PREC/L monthly land precipitation at 0.5 degree",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="0.5 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/precl/0.5deg/",
            "filename_pattern": "precip.mon.mean.0.5x0.5.nc",
            "time_expansion": "none",
        },
        aliases=("precl", "precl_05deg", "prec_l"),
        format_hints=("NetCDF",),
        notes="NOAA PREC/L land-only monthly precipitation on the 0.5 degree grid.",
        official_url="https://psl.noaa.gov/data/gridded/data.precl.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="PSL THREDDS exposes the current full-series NetCDF as a single file.",
    ),
    DataSource(
        key="precl_monthly_1deg_nc",
        title="PREC/L monthly land precipitation at 1.0 degree",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="1.0 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/precl/1.0deg/",
            "filename_pattern": "precip.mon.mean.1x1.nc",
            "time_expansion": "none",
        },
        aliases=("precl_1deg",),
        format_hints=("NetCDF",),
        notes="NOAA PREC/L land-only monthly precipitation on the 1 degree grid.",
        official_url="https://psl.noaa.gov/data/gridded/data.precl.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="PSL THREDDS exposes the current full-series NetCDF as a single file.",
    ),
    DataSource(
        key="precl_monthly_25deg_nc",
        title="PREC/L monthly land precipitation at 2.5 degree",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="2.5 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/precl/2.5deg/",
            "filename_pattern": "precip.mon.mean.2.5x2.5.nc",
            "time_expansion": "none",
        },
        aliases=("precl_25deg",),
        format_hints=("NetCDF",),
        notes="NOAA PREC/L land-only monthly precipitation on the 2.5 degree grid.",
        official_url="https://psl.noaa.gov/data/gridded/data.precl.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="PSL THREDDS exposes the current full-series NetCDF as a single file.",
    ),
    DataSource(
        key="era5_single_levels_hourly",
        title="ERA5 hourly data on single levels",
        variables=(
            "2m_temperature",
            "total_precipitation",
            "potential_evaporation",
            "runoff",
            "surface_runoff",
            "sub_surface_runoff",
            "volumetric_soil_water_layer_1",
            "volumetric_soil_water_layer_2",
            "volumetric_soil_water_layer_3",
            "volumetric_soil_water_layer_4",
        ),
        temporal_resolution="hourly",
        spatial_resolution="0.25 degree",
        provider="Copernicus Climate Data Store",
        method="cds_api",
        params={
            "dataset_name": "reanalysis-era5-single-levels",
            "default_data_format": "grib",
            "default_download_format": "unarchived",
            "time_mode": "hourly_all",
        },
        aliases=("era5",),
        format_hints=("GRIB", "NetCDF"),
        notes="ERA5 global hourly single-level reanalysis from CDS.",
        official_url="https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels",
        access_mode="api",
        auth_required=True,
        product_notes="Designed for the same CDS API flow already used by the ERA5-Land downloader.",
    ),
    DataSource(
        key="era5land_hourly",
        title="ERA5-Land hourly data",
        variables=(
            "2m_temperature",
            "total_precipitation",
            "potential_evaporation",
            "runoff",
            "surface_runoff",
            "sub_surface_runoff",
            "snow_depth_water_equivalent",
            "volumetric_soil_water_layer_1",
            "volumetric_soil_water_layer_2",
            "volumetric_soil_water_layer_3",
            "volumetric_soil_water_layer_4",
        ),
        temporal_resolution="hourly",
        spatial_resolution="0.1 degree",
        provider="Copernicus Climate Data Store",
        method="cds_api",
        params={
            "dataset_name": "reanalysis-era5-land",
            "default_data_format": "grib",
            "default_download_format": "unarchived",
            "time_mode": "hourly_all",
        },
        aliases=("era5land",),
        format_hints=("GRIB", "NetCDF"),
        notes="ERA5-Land hourly data from 1950 to present.",
        official_url="https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land",
        access_mode="api",
        auth_required=True,
        product_notes="Recommended first acquisition test uses a single variable, single day, and GRIB output.",
    ),
    DataSource(
        key="imerg_final_hdf5",
        title="IMERG Final Run HDF5",
        variables=("precipitation",),
        temporal_resolution="half-hourly to daily",
        spatial_resolution="0.1 degree",
        provider="NASA GPM / PPS archive",
        method="http_listing",
        params={
            "base_url": "https://arthurhouhttps.pps.eosdis.nasa.gov/gpmdata/",
            "directory_pattern": "{year}/{month}/{day}/imerg/",
            "file_regex": r'href="([^"]+\.HDF5)"',
            "contains": ["3imerg"],
            "time_expansion": "date",
            "file_limit_default": 1,
        },
        aliases=("imerg",),
        format_hints=("HDF5",),
        notes="IMERG Final Run HDF5 files for research applications.",
        official_url="https://gpm.nasa.gov/data/imerg",
        access_mode="https_listing",
        auth_required=True,
        product_notes="Downloader targets PPS archive-style daily directory listing and selects HDF5 files automatically.",
    ),
    DataSource(
        key="gleam_monthly_nc",
        title="GLEAM monthly NetCDF",
        variables=(
            "potential_evaporation",
            "evapotranspiration",
            "surface_soil_moisture",
            "root_zone_soil_moisture",
            "soil_moisture",
            "transpiration",
            "interception_loss",
            "soil_evaporation",
            "open_water_evaporation",
        ),
        temporal_resolution="monthly",
        spatial_resolution="0.1 degree",
        provider="GLEAM project",
        method="sftp",
        params={
            "default_port": 2225,
            "variable_directory_map": {
                "potential_evaporation": "Ep",
                "evapotranspiration": "E",
                "surface_soil_moisture": "SMs",
                "root_zone_soil_moisture": "SMrz",
                "soil_moisture": "SMs",
                "transpiration": "Et",
                "interception_loss": "Ei",
                "soil_evaporation": "Es",
                "open_water_evaporation": "Ew",
            },
            "file_limit_default": 1,
        },
        aliases=("gleam",),
        format_hints=("NetCDF",),
        notes="GLEAM monthly NetCDF files accessed through registered SFTP download.",
        official_url="https://www.gleam.eu/",
        access_mode="sftp",
        auth_required=True,
        product_notes="Official access requires registration; FAQ specifies SFTP on port 2225.",
    ),
    DataSource(
        key="mswep_monthly_nc",
        title="MSWEP monthly NetCDF via Rclone",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="0.1 degree",
        provider="GloH2O / MSWEP team",
        method="rclone",
        params={"default_subdir": "Monthly", "file_limit_default": None},
        aliases=("mswep",),
        format_hints=("NetCDF",),
        notes="MSWEP monthly precipitation downloaded via Rclone shared Google Drive access.",
        official_url="https://www.gloh2o.org/",
        access_mode="rclone_shared_drive",
        auth_required=True,
        product_notes="Noncommercial users download through Rclone using the shared Google Drive folder referenced in the MSWEP access email.",
    ),
    DataSource(
        key="mswep_daily_nc",
        title="MSWEP daily NetCDF via Rclone",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.1 degree",
        provider="GloH2O / MSWEP team",
        method="rclone",
        params={"default_subdir": "Daily", "file_limit_default": None},
        format_hints=("NetCDF",),
        notes="MSWEP daily precipitation downloaded via Rclone shared Google Drive access.",
        official_url="https://www.gloh2o.org/",
        access_mode="rclone_shared_drive",
        auth_required=True,
        product_notes="Noncommercial users download through Rclone using the shared Google Drive folder referenced in the MSWEP access email.",
    ),
    DataSource(
        key="persiann_cdr_erddap",
        title="PERSIANN-CDR via NOAA ERDDAP",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.25 degree",
        provider="NOAA NCEI / UC Irvine CHRS",
        method="erddap",
        params={
            "base_url": "https://www.ncei.noaa.gov/erddap/griddap/cdr_persiann_by_time_lon_lat.nc",
            "query_variable": "precipitation",
            "default_bbox": (0.125, -59.875, 359.875, 59.875),
            "time_step": 1,
            "lat_step": 1,
            "lon_step": 1,
        },
        format_hints=("NetCDF",),
        notes="PERSIANN-CDR daily precipitation accessed through NOAA ERDDAP subset service.",
        official_url="https://www.ncei.noaa.gov/erddap/griddap/cdr_persiann_by_time_lon_lat.html",
        access_mode="http_erddap",
        auth_required=False,
        product_notes="Daily quasi-global precipitation; automated subset downloads are supported through NOAA ERDDAP.",
    ),
    DataSource(
        key="persiann_portal",
        title="PERSIANN via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="hourly to accumulative",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="persiann_ccs_portal",
        title="PERSIANN-CCS via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="hourly to accumulative",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN-CCS.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="persiann_cdr_portal",
        title="PERSIANN-CDR via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="daily to monthly",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN-CDR.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Portal family entry. A separate NOAA ERDDAP downloader can also be maintained for automated PERSIANN-CDR access.",
    ),
    DataSource(
        key="persiann_ccs_cdr_v2_portal",
        title="PERSIANN-CCS-CDR V2.0 via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="hourly to accumulative",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN-CCS-CDR V2.0.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="pdir_now_portal",
        title="PDIR-Now via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="hourly to accumulative",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PDIR-Now.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="persiann_v3_portal",
        title="PERSIANN V3 via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="hourly to accumulative",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN V3.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="persiann_cdr_v3_portal",
        title="PERSIANN-CDR V3 via CHRS Data Portal",
        variables=("precipitation",),
        temporal_resolution="daily to monthly",
        spatial_resolution="portal-defined",
        provider="CHRS Data Portal",
        method="portal_export",
        params={},
        format_hints=("ArcGrid", "GeoTIFF", "NetCDF"),
        notes="Portal-based download workflow for PERSIANN-CDR V3.",
        official_url="https://chrsdata.eng.uci.edu/",
        access_mode="portal_export",
        auth_required=False,
        product_notes="Part of the current PERSIANN family product set available through the CHRS portal.",
    ),
    DataSource(
        key="cmfd",
        title="China Meteorological Forcing Dataset",
        variables=("precipitation", "temperature", "humidity", "radiation", "wind", "pressure"),
        temporal_resolution="3-hourly to monthly",
        spatial_resolution="0.1 degree",
        provider="National Tibetan Plateau Data Center",
        method="ftp",
        params={
            "host": "ftp2.tpdc.ac.cn",
            "port": 6201,
            "remote_base_dir": "/",   # 这里后面需要你登录后确认真实目录
            "time_expansion": "none", # 先占位，后面看文件命名规则再改
            "file_limit_default": None,
        },
        format_hints=("NetCDF",),
        notes="CMFD accessed through TPDC authenticated FTP service.",
        official_url="https://data.tpdc.ac.cn/",
        access_mode="ftp",
        auth_required=True,
        product_notes="Authenticated FTP account required.",
    ),
    DataSource(
        key="cmfd v2",
        title="China Meteorological Forcing Dataset",
        variables=("precipitation", "temperature", "humidity", "radiation", "wind", "pressure"),
        temporal_resolution="3-hourly to monthly",
        spatial_resolution="0.1 degree",
        provider="National Tibetan Plateau Data Center",
        method="ftp",
        params={
            "host": "ftp2.tpdc.ac.cn",
            "port": 6201,
            "remote_base_dir": "/",   # 这里后面需要你登录后确认真实目录
            "time_expansion": "none", # 先占位，后面看文件命名规则再改
            "file_limit_default": None,
        },
        format_hints=("NetCDF",),
        notes="CMFD accessed through TPDC authenticated FTP service.",
        official_url="https://data.tpdc.ac.cn/",
        access_mode="ftp",
        auth_required=True,
        product_notes="Authenticated FTP account required.",
    ),
    DataSource(
        key="cmorph_daily_025deg_ftp",
        title="CMORPH daily 0.25 degree via FTP",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.25 degree",
        provider="NOAA CPC",
        method="ftp",
        params={
            "host": "ftp.cpc.ncep.noaa.gov",
            "remote_base_dir": "/precip/global_CMORPH/daily_025deg",
            "filename_pattern": "CMORPH+MWCOMB_DAILY-025DEG_{date}.Z",
            "time_expansion": "date",
        },
        aliases=("cmorph", "cmorph_daily"),
        format_hints=("Z-compressed binary",),
        notes="Daily CMORPH 0.25 degree files on the CPC FTP server.",
        official_url="https://ftp.cpc.ncep.noaa.gov/precip/global_CMORPH/daily_025deg/",
        access_mode="ftp",
        auth_required=False,
        product_notes="One compressed file per day.",
    ),
    DataSource(
        key="cmorph_3hourly_025deg_ftp",
        title="CMORPH 3-hourly 0.25 degree via FTP",
        variables=("precipitation",),
        temporal_resolution="3-hourly",
        spatial_resolution="0.25 degree",
        provider="NOAA CPC",
        method="ftp",
        params={
            "host": "ftp.cpc.ncep.noaa.gov",
            "remote_base_dir": "/precip/global_CMORPH/3-hourly_025deg",
            "filename_pattern": "CMORPH+MWCOMB_3HRLY-025DEG_{date}.Z",
            "time_expansion": "date",
        },
        aliases=("cmorph_3hourly",),
        format_hints=("Z-compressed binary",),
        notes="3-hourly CMORPH 0.25 degree daily aggregate containers on the CPC FTP server.",
        official_url="https://ftp.cpc.ncep.noaa.gov/precip/global_CMORPH/3-hourly_025deg/",
        access_mode="ftp",
        auth_required=False,
        product_notes="One compressed file per day, each containing 3-hourly fields.",
    ),
    DataSource(
        key="cmorph_30min_025deg_ftp",
        title="CMORPH 30-minute 0.25 degree via FTP",
        variables=("precipitation",),
        temporal_resolution="30-minute",
        spatial_resolution="0.25 degree",
        provider="NOAA CPC",
        method="ftp",
        params={
            "host": "ftp.cpc.ncep.noaa.gov",
            "remote_base_dir": "/precip/global_CMORPH/30min_025deg",
            "time_expansion": "date",
            "file_regex": r"CMORPH_025DEG-30MIN_.*\.Z$",
            "contains_template": "{date}",
            "filename_date_regex": r"(?P<date>\d{10})",
        },
        aliases=("cmorph_30min",),
        format_hints=("Z-compressed binary",),
        notes="Flat FTP directory containing many CMORPH 30-minute files; downloader filters by the requested date token.",
        official_url="https://ftp.cpc.ncep.noaa.gov/precip/global_CMORPH/30min_025deg/",
        access_mode="ftp",
        auth_required=False,
        product_notes="For each requested date, all matching sub-daily files are selected from the flat directory listing.",
    ),
    DataSource(
        key="cmorph_daily_025deg_http",
        title="CMORPH daily 0.25 degree via NCEI HTTP listing",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.25 degree",
        provider="NOAA NCEI",
        method="http_listing",
        params={
            "base_url": "https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/daily/0.25deg/",
            "directory_pattern": "{year}/{month}/",
            "time_expansion": "date",
            "file_regex": r'href="([^"]+)"',
            "file_limit_default": None,
        },
        aliases=("cmorph_daily_http",),
        format_hints=("NetCDF", "Binary", "GZip", "BZ2"),
        notes="NCEI public HTTP directory listing for CMORPH daily 0.25 degree data.",
        official_url="https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/",
        access_mode="http_listing",
        auth_required=False,
    ),
    DataSource(
        key="cmorph_hourly_025deg_http",
        title="CMORPH hourly 0.25 degree via NCEI HTTP listing",
        variables=("precipitation",),
        temporal_resolution="hourly",
        spatial_resolution="0.25 degree",
        provider="NOAA NCEI",
        method="http_listing",
        params={
            "base_url": "https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/hourly/0.25deg/",
            "directory_pattern": "{year}/{month}/{day}/",
            "time_expansion": "date",
            "file_regex": r'href="([^"]+)"',
            "file_limit_default": None,
        },
        aliases=("cmorph_hourly_http",),
        format_hints=("NetCDF", "Binary", "GZip", "BZ2"),
        notes="NCEI public HTTP directory listing for CMORPH hourly 0.25 degree data.",
        official_url="https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/",
        access_mode="http_listing",
        auth_required=False,
    ),
    DataSource(
        key="cmorph_30min_8km_http",
        title="CMORPH 30-minute 8 km via NCEI HTTP listing",
        variables=("precipitation",),
        temporal_resolution="30-minute",
        spatial_resolution="8 km",
        provider="NOAA NCEI",
        method="http_listing",
        params={
            "base_url": "https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/30min/8km/",
            "directory_pattern": "{year}/{month}/{day}/",
            "time_expansion": "date",
            "file_regex": r'href="([^"]+)"',
            "file_limit_default": None,
        },
        aliases=("cmorph_30min_http",),
        format_hints=("NetCDF", "Binary", "GZip", "BZ2"),
        notes="NCEI public HTTP directory listing for CMORPH 30-minute 8 km data.",
        official_url="https://www.ncei.noaa.gov/data/cmorph-high-resolution-global-precipitation-estimates/access/",
        access_mode="http_listing",
        auth_required=False,
    ),
    DataSource(
        key="cmap_monthly_std_nc",
        title="CMAP standard monthly precipitation",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="2.5 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/cmap/std/",
            "filename_pattern": "precip.mon.mean.nc",
            "time_expansion": "none",
        },
        aliases=("cmap",),
        format_hints=("NetCDF",),
        notes="Single rolling NetCDF file for the standard CMAP monthly product.",
        official_url="https://psl.noaa.gov/data/gridded/data.cmap.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="The current file contains the standard monthly CMAP time series.",
    ),
    DataSource(
        key="gpcp_monthly_v23_ncei",
        title="GPCP monthly v2.3 via NCEI access directory",
        variables=("precipitation",),
        temporal_resolution="monthly",
        spatial_resolution="2.5 degree",
        provider="NOAA NCEI",
        method="http_listing",
        params={
            "base_url": "https://www.ncei.noaa.gov/data/global-precipitation-climatology-project-gpcp-monthly/access/",
            "directory_pattern": "{year}/",
            "time_expansion": "year",
            "file_regex": r'href="([^"]+\.nc)"',
            "filename_date_regex": r"d(?P<yearmonth>\d{6})",
        },
        aliases=("gpcp", "gpcp_monthly"),
        format_hints=("NetCDF",),
        notes="NCEI monthly access tree where each year folder contains monthly NetCDF files.",
        official_url="https://www.ncei.noaa.gov/data/global-precipitation-climatology-project-gpcp-monthly/access/",
        access_mode="http_listing",
        auth_required=False,
        product_notes="Downloader lists each requested year folder and filters files by the embedded YYYYMM token.",
    ),
    DataSource(
        key="gpcp_daily_cdr_v1_3_nc",
        title="GPCP daily CDR v1.3 via NCEI access directory",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="1.0 degree",
        provider="NOAA NCEI",
        method="http_listing",
        params={
            "base_url": "https://www.ncei.noaa.gov/data/global-precipitation-climatology-project-gpcp-daily/access/",
            "directory_pattern": "{year}/",
            "file_regex": r'href="([^"]+\.nc)"',
            "contains_template": ["d{date}"],
            "filename_date_regex": r'd(?P<date>\d{8})',
            "time_expansion": "date",
            "file_limit_default": None,
        },
        aliases=("gpcp_daily", "gpcp_1dd"),
        format_hints=("NetCDF",),
        notes="NCEI access directory exposes one NetCDF granule per day for the GPCP daily CDR.",
        official_url="https://www.ncei.noaa.gov/products/climate-data-records/precipitation-gpcp-daily",
        access_mode="https_listing",
        auth_required=False,
        product_notes="Directory names are annual and filenames contain the target date token as dYYYYMMDD.",
    ),
    DataSource(
        key="ncep_ncar_reanalysis1_prate_monthly_nc",
        title="NCEP NCAR Reanalysis 1 monthly precipitation rate",
        variables=("precipitation", "prate"),
        temporal_resolution="monthly",
        spatial_resolution="2.5 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/ncep.reanalysis/Monthlies/surface/",
            "filename_pattern": "prate.mon.mean.nc",
            "time_expansion": "none",
        },
        aliases=("ncep", "ncep_ncar", "ncep_ncar_reanalysis"),
        format_hints=("NetCDF",),
        notes="Single rolling monthly precipitation-rate NetCDF from the surface directory.",
        official_url="https://psl.noaa.gov/data/gridded/data.ncep.reanalysis.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="This entry targets the monthly surface precipitation-rate file exposed by the PSL THREDDS server.",
    ),
    DataSource(
        key="twentieth_century_reanalysis_v3_prate_monthly_nc",
        title="20th Century Reanalysis V3 monthly precipitation rate",
        variables=("precipitation", "prate"),
        temporal_resolution="monthly",
        spatial_resolution="1 degree",
        provider="NOAA PSL",
        method="http_direct",
        params={
            "base_url": "https://downloads.psl.noaa.gov/Datasets/20thC_ReanV3/Monthlies/sfcMO/",
            "filename_pattern": "prate.mon.mean.nc",
            "time_expansion": "none",
        },
        aliases=("20cr", "20cr_v3", "twentieth_century_reanalysis"),
        format_hints=("NetCDF",),
        notes="Single rolling monthly precipitation-rate NetCDF from the 20CR V3 sfcMO directory.",
        official_url="https://psl.noaa.gov/data/gridded/data.20thC_ReanV3.html",
        access_mode="direct_http",
        auth_required=False,
        product_notes="Targets the monthly mean prate field available from the PSL THREDDS fileServer path.",
    ),
    DataSource(
        key="trmm_3b42_daily_v7",
        title="TRMM TMPA 3B42 Daily Version 7 via NASA Earthdata CMR",
        variables=("precipitation",),
        temporal_resolution="daily",
        spatial_resolution="0.25 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "TRMM_3B42_Daily",
            "version": "7",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
        },
        aliases=("trmm", "trmm_tmpa", "trmm_daily", "tmpa_daily"),
        format_hints=("HDF", "NetCDF"),
        notes="Daily TRMM TMPA research product discovered from CMR granule search and downloaded through Earthdata-authenticated HTTPS.",
        official_url="https://www.earthdata.nasa.gov/data/catalog/ges-disc-trmm-3b42-daily-7",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="The official Earthdata page notes that the product was discontinued after December 31 2019 and recommends IMERG for newer periods.",
    ),
    DataSource(
        key="trmm_3b42_3hourly_v7",
        title="TRMM TMPA 3B42 3-hourly Version 7 via NASA Earthdata CMR",
        variables=("precipitation",),
        temporal_resolution="3-hourly",
        spatial_resolution="0.25 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "TRMM_3B42",
            "version": "7",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
        },
        aliases=("trmm_3hourly", "tmpa_3hourly"),
        format_hints=("HDF", "NetCDF"),
        notes="3-hourly TRMM TMPA research product discovered from CMR granule search and downloaded through Earthdata-authenticated HTTPS.",
        official_url="https://www.earthdata.nasa.gov/data/catalog/ges-disc-trmm-3b42-7",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="The official Earthdata page notes that the product was discontinued after December 31 2019 and recommends IMERG for newer periods.",
    ),
    DataSource(
        key="merra2_tavg1_2d_flx_nx_hourly",
        title="MERRA-2 hourly surface flux diagnostics via NASA Earthdata CMR",
        variables=("precipitation", "evaporation", "surface_fluxes"),
        temporal_resolution="hourly",
        spatial_resolution="0.5 x 0.625 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "M2T1NXFLX",
            "version": "5.12.4",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("merra2", "merra2_hourly", "m2t1nxflx"),
        format_hints=("NetCDF-4",),
        notes="Hourly MERRA-2 surface flux diagnostics, including precipitation-related fields, discovered from CMR granule search.",
        official_url="https://cmr.earthdata.nasa.gov/search/concepts/C1215802938-GES_DISC",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="Useful when the acquisition target is precipitation and related surface flux terms from the hourly MERRA-2 archive.",
    ),
    DataSource(
        key="merra2_tavg1_2d_slv_nx_hourly",
        title="MERRA-2 hourly single-level diagnostics via NASA Earthdata CMR",
        variables=("temperature", "humidity", "wind", "pressure"),
        temporal_resolution="hourly",
        spatial_resolution="0.5 x 0.625 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "M2T1NXSLV",
            "version": "5.12.4",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("merra2_slv", "m2t1nxslv"),
        format_hints=("NetCDF-4",),
        notes="Hourly MERRA-2 single-level diagnostics discovered from CMR granule search.",
        official_url="https://cmr.earthdata.nasa.gov/search/concepts/C1276812863-GES_DISC",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="Useful when the acquisition target is temperature, humidity, wind, or pressure from MERRA-2.",
    ),
    DataSource(
        key="merra2_tavgm_2d_flx_nx_monthly",
        title="MERRA-2 monthly surface flux diagnostics via NASA Earthdata CMR",
        variables=("precipitation", "evaporation", "surface_fluxes"),
        temporal_resolution="monthly",
        spatial_resolution="0.5 x 0.625 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "M2TMNXFLX",
            "version": "5.12.4",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("merra2_monthly", "m2tmnxflx"),
        format_hints=("NetCDF-4",),
        notes="Monthly MERRA-2 surface flux diagnostics discovered from CMR granule search.",
        official_url="https://cmr.earthdata.nasa.gov/search/concepts/C1276812868-GES_DISC",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="Useful when monthly precipitation and evaporation diagnostics are sufficient and much lighter than hourly downloads.",
    ),
    DataSource(
        key="gldas_noah025_3h_v21",
        title="GLDAS Noah 0.25 degree 3-hourly Version 2.1 via NASA Earthdata CMR",
        variables=("precipitation", "soil_moisture", "runoff", "temperature", "evapotranspiration"),
        temporal_resolution="3-hourly",
        spatial_resolution="0.25 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "GLDAS_NOAH025_3H",
            "version": "2.1",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("gldas", "gldas_noah025", "gldas_3h"),
        format_hints=("NetCDF-4",),
        notes="GLDAS Noah 3-hourly 0.25 degree archive discovered from CMR granule search.",
        official_url="https://www.earthdata.nasa.gov/data/catalog/ges-disc-gldas-noah025-3h-2.1",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="This is the main production stream product described on the current Earthdata landing page.",
    ),
    DataSource(
        key="fldas_noah01_c_gl_m_v001",
        title="FLDAS Noah global monthly Version 001 via NASA Earthdata CMR",
        variables=("precipitation", "soil_moisture", "runoff", "temperature", "evapotranspiration"),
        temporal_resolution="monthly",
        spatial_resolution="0.1 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "FLDAS_NOAH01_C_GL_M",
            "version": "001",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("fldas", "fldas_monthly", "fldas_noah01"),
        format_hints=("NetCDF-4",),
        notes="FLDAS global monthly archive based on MERRA-2 and CHIRPS forcing, discovered from CMR granule search.",
        official_url="https://cmr.earthdata.nasa.gov/search/concepts/C1563089663-GES_DISC",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="The currently discoverable global FLDAS collection in the main lineage is monthly rather than 3-hourly.",
    ),
    DataSource(
        key="fldas_noah01_cp_gl_m_v001",
        title="FLDAS Noah global monthly GDAS and CHIRPS-PRELIM Version 001 via NASA Earthdata CMR",
        variables=("precipitation", "soil_moisture", "runoff", "temperature", "evapotranspiration"),
        temporal_resolution="monthly",
        spatial_resolution="0.1 degree",
        provider="NASA GES DISC / Earthdata",
        method="earthdata_cmr",
        params={
            "short_name": "FLDAS_NOAH01_CP_GL_M",
            "version": "001",
            "provider": "GES_DISC",
            "preferred_link_substrings": ["gesdisc", "disc"],
            "filename_regex": r"\.(nc4|nc)$",
        },
        aliases=("fldas_cp", "fldas_chirps_prelim"),
        format_hints=("NetCDF-4",),
        notes="FLDAS monthly archive forced by GDAS and CHIRPS-PRELIM, discovered from CMR granule search.",
        official_url="https://cmr.earthdata.nasa.gov/search/concepts/C2020765110-GES_DISC",
        access_mode="earthdata_cmr_https",
        auth_required=True,
        product_notes="This branch starts in 2019 and represents the CHIRPS-PRELIM forcing stream shown on the current Earthdata landing page.",
    ),
    DataSource(
        key="cmip6_esgf",
        title="CMIP6 via ESGF",
        variables=("tas", "tasmax", "tasmin", "pr", "rsds", "hurs", "sfcWind", "mrro", "mrros", "mrsos"),
        temporal_resolution="model-dependent",
        spatial_resolution="model-dependent",
        provider="ESGF / WCRP CMIP",
        method="esgf",
        params={
            "project": "CMIP6",
            "default_search_node": "https://esgf-node.llnl.gov/esg-search/search",
            "default_wget_node": "https://esgf-node.llnl.gov/esg-search/wget",
            "default_type": "File",
            "latest": "true",
            "replica": "false",
            "distrib": "true",
        },
        format_hints=("NetCDF",),
        notes="CMIP6 datasets accessed via ESGF Search API and wget script generation.",
        official_url="https://wcrp-cmip.org/cmip-data-access/",
        access_mode="esgf_search_and_wget",
        auth_required=True,
        product_notes="CMIP6 data are distributed through ESGF.",
    ),
    DataSource(
        key="cmip5_esgf",
        title="CMIP5 via ESGF",
        variables=("tas", "tasmax", "tasmin", "pr", "rsds", "hurs", "sfcWind", "mrro", "mrros", "mrsos"),
        temporal_resolution="model-dependent",
        spatial_resolution="model-dependent",
        provider="ESGF / WCRP CMIP",
        method="esgf",
        params={
            "project": "CMIP5",
            "default_search_node": "https://esgf-node.llnl.gov/esg-search/search",
            "default_wget_node": "https://esgf-node.llnl.gov/esg-search/wget",
            "default_type": "File",
            "latest": "true",
            "replica": "false",
            "distrib": "true",
        },
        format_hints=("NetCDF",),
        notes="CMIP5 datasets accessed via ESGF Search API and wget script generation.",
        official_url="https://wcrp-cmip.org/cmip-data-access/",
        access_mode="esgf_search_and_wget",
        auth_required=True,
        product_notes="CMIP5 downloads are distributed through ESGF.",
    ),
)


def _all_names(src: DataSource) -> set[str]:
    return {src.key.lower(), *[a.lower() for a in src.aliases]}


def _unique_sources() -> list[DataSource]:
    seen: set[str] = set()
    unique: list[DataSource] = []
    for src in DEFAULT_SOURCES:
        key = src.key.lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(src)
    return unique


def list_sources(variable: str | None = None) -> list[DataSource]:
    sources = _unique_sources()
    if variable is None:
        return sources
    variable = variable.lower().strip()
    return [src for src in sources if variable in {v.lower() for v in src.variables}]


def search_sources(keyword: str) -> list[DataSource]:
    token = keyword.lower().strip().replace("_", " ")
    hits: list[DataSource] = []
    for src in _unique_sources():
        haystack = " ".join(
            (
                src.key,
                *src.aliases,
                src.title,
                src.provider,
                src.notes,
                src.product_notes,
                src.access_mode,
                *src.variables,
            )
        ).lower().replace("_", " ")
        if token in haystack:
            hits.append(src)
    return hits


def get_source(source_key: str) -> DataSource:
    key = source_key.lower().strip()
    for src in _unique_sources():
        if key in _all_names(src):
            return src
    raise KeyError(f"No source configuration found for source_key='{source_key}'")
